# Este docker-compose.local.minio.yml permite levantar LLDAP en el entorno local.
# Se ejecuta con el comando:
# - docker compose --env-file .env.local -f docker-compose.lldap.yaml up

name: picudo-rojo-project

services:
  lldap:
    image: lldap/lldap:${LLDAP_VERSION:-stable}
    ports:
      - "3890:3890" # Para LDAP, no es necesario si se comunican entre contenedores
      - "17170:17170" # Web UI
    volumes:
      - "./lldap_data:/data"
    environment:
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=dc=localhost,dc=local # Base DN
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS:-adminPas$word}
    networks:
      - main

networks:
  main: