[project]
name = "modulo-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
# uv build # En el modulo utilidades
# uv add dist/modulo_utilidades-0.1.0-py3-none-any.whl
# uv add "modulo-utilidades @E:\Documentos\Git Repositories\uba-ceia-proy-final\ceia-proyecto-final\modulo-utilidades\dist\modulo_utilidades-0.1.0-py3-none-any.whl"
dependencies = [
    "loguru>=0.7.3",
    "modulo-utilidades",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "supervision>=0.26.1",
    "ultralytics>=8.3.217",
]

# Formas de instalar el modulo-utilidades:
# - Como dependencia de desarrollo (ej: para tests, notebooks, scripts de ayuda, que no es necesario en producción)::
# uv add "modulo-utilidades @ ..\modulo-utilidades\" --dev --no-editable # Instala todo, pero no se puede editar el modulo utilidades sobre la marcha.
# uv add "modulo-utilidades @ ..\modulo-utilidades\" --dev --editable # No instala dependencias de desarrollo, hay que instalarlas a mano. Te explota si no lo haces.
# uv add --group dev "modulo-utilidades @ ..\modulo-utilidades\"    # Instalar dependencias de desarrollo (si existe el grupo dev en el modulo utilidades). Permite editar el modulo utilidades sobre la marcha.
                                                                    # Sin embargo, se instala y la ruta queda por defecto en el .venv del modulo IA, lo que hace fallar las configuraciones que cargan variables 
                                                                    # de entorno desde el .env del modulo utilidades.

# La mejor forma es definir un grupo dev en el modulo utilidades, y luego instalarlo con:
# uv add "modulo-utilidades[dev] @ ..\modulo-utilidades\" --dev --editable 
# O sea, instalar el grupo dev del modulo utilidades en modo editable en el entorno de desarrollo del modulo IA. Pero esto daba problemas con
# el .env, por lo que la solución final fue instalarlo como --optional dev

# - Como dependencia del código productivo:
#     - Modo editable (los cambios en el modulo utilidades se reflejan al instante en el modulo IA):
# uv add "modulo-utilidades @ ..\modulo-utilidades\" --editable
#     - Modo producción (no se pueden editar los archivos del modulo utilidades sobre la marcha):
# uv build # En el modulo-utilidades (crea la Wheel)
# uv add "modulo-utilidades @E:\Documentos\Git Repositories\uba-ceia-proy-final\ceia-proyecto-final\modulo-utilidades\dist\modulo_utilidades-0.1.0-py3-none-any.whl"

# No se utiliza la dependencia "dependency-groups" por defecto de uv, sino que se utiliza la sección [project.optional-dependencies]
# para definir las dependencias de desarrollo.
# [dependency-groups]
# dev = [
#     ...
# ]

# Para agregar dependencias: uv add <dependencia> --optional dev
[project.optional-dependencies]
dev = [
    "tqdm>=4.67.1",
    "scikit-learn>=1.7.0",
    "fiftyone>=1.6.0",
    "mlflow>=3.1.1",
    "deprecated>=1.2.18",
    "sahi>=0.11.32",
    "ipykernel>=6.30.1",
    "torchvision>=0.22.1",
    "torch>=2.7.1",
    "python-dotenv>=1.1.1",
    "typer>=0.19.2",
    "gputil-fix>=1.4.1.2",
    "modulo-utilidades[dev]",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
# Advertencia: Hay que ver el CUDA que se va a utilizar en producción.
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
modulo-utilidades = { path = "wheels/modulo_utilidades-0.1.0-py3-none-any.whl" }

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "modulo_ia"
module-root = ""
source-exclude = [
    "modulo_ia/utils",
    "modulo_ia/dataset.py",
    "modulo_ia/features.py",
    "modulo_ia/main.py",
    "modulo_ia/visualizations.py",
]
