# Configuración general
environment: "LOCAL" # Opciones: PRODUCTION, LOCAL, SCALEWAY

# Logger
logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s - %(message)s"
  level: "INFO"

# MongoDB
mongodb:
  database: ${MONGODB_INITDB_DATABASE}
  host: ${MONGODB_SERVER_HOST}
  port: ${MONGODB_SERVER_PORT}
  user: ${MONGODB_USER}
  password: ${MONGODB_PASSWORD}
  connection_string: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_SERVER_HOST}:${MONGODB_SERVER_PORT}/${MONGODB_INITDB_DATABASE}"

cvat:
  url: ${CVAT_URL}
  user: ${CVAT_USER}
  password: ${CVAT_PASSWORD}
  export_format: "COCO 1.0"
  task_export_path: "annotations\\instances_default.json"
  job_export_path: "annotations\\instances_default.json"

coco_dataset:
  info:
    description: "Conjunto de imágenes para la detección del picudo rojo"
    url: "https://picudo-rojo.org"
    version: "1.0"
    year: 2025
    contributor: "Intendencia de Montevideo"
    date_created: "2025/01/01"
  licenses:
    - id: 1
      name: "CC BY-NC-SA 4.0"
      url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  categories:
    - id: 1
      name: "palmera-sana"
      supercategory: ""
    - id: 2
      name: "palmera-inf-leve"
      supercategory: ""
    - id: 3
      name: "palmera-inf-grave"
      supercategory: ""
    - id: 4
      name: "palmera-muerta"
      supercategory: ""
    - id: 5
      name: "palmera"
      supercategory: ""

download_folder: "downloads"
