http:
  routers:
    ldap-ssp-router:
      rule: "Host(`password.picudo-rojo.org`)"
      service: ldap-ssp-service
    
    cvat-router:
      rule: "Host(`cvat.picudo-rojo.org`)"
      service: cvat-service

    # fiftyone-router:
    #   rule: "Host(`fiftyone.picudo-rojo.org`)"
    #   service: fiftyone-service

    landing-page-router:
      rule: "Host(`picudo-rojo.org`)"
      service: landing-page-service

    # Testing router:
    # landing-page-router:
    #   rule: "PathPrefix(`/`)"
    #   service: landing-page-service

  services:
    cvat-service:
      loadBalancer:
        servers:
          # - url: "http://host.docker.internal:8080" # Windows
          - url: "http://traefik:8080"

    # fiftyone-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://host.docker.internal:5151" # Windows

    landing-page-service:
      loadBalancer:
        servers:
          # - url: "http://host.docker.internal:9100" # Windows
          - url: "http://landing-page:80" # Linux

    ldap-ssp-service:
      loadBalancer:
        servers:
          # - url: "http://host.docker.internal:17171" # Windows
          - url: "http://ldap-ssp:80" # Linux
