name: picudo-rojo-project # Incluir todos las aplicaciones en un mismo proyecto.

services:
  minio:
    volumes:
      - ./minio-certs:/root/.minio/certs:ro # Montar los certificados de Minio

  mc:
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio https://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD) do sleep 1; done;
      /usr/bin/mc mb myminio/${MINIO_INITIAL_BUCKET};
      /usr/bin/mc policy set public myminio/${MINIO_INITIAL_BUCKET};
      exit 0;
      "