[project]
name = "modulo-utilidades"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
# requires-python = ">=3.13, <4.0" # Version original
requires-python = ">=3.11" # Versión adaptada a GPU NVIDIA GTX 1060
dependencies = [
    "fastkml>=1.2.0",
    "geopandas>=1.1.1",
    "loguru>=0.7.3",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "shapely>=2.1.2",
    "supervision>=0.26.1",
]

# Bien, para importar en el otro módulo (IA), dado que uv no propaga grupos, no se define este grupo, sino en el extra [project.optional-dependencies]
# Esto es porque al importar este módulo en el modulo-ia, no se reconocían las dependencias del grupo dev.
# Al hacerlo desde optional-dependencies, se soluciona el problema, dado que los extras sí se propagan.
# [dependency-groups] # No se usa más esta sección
# dev = [
#     "loguru>=0.7.3",
#     ...
# ]
# El grupo dependency-groups son para módulos de desarrollo del mismo paquete, no para que otros módulos los importen.

[project.optional-dependencies]
development = [
    "pymongo>=4.9.2",
    "boto3>=1.38.44",
    "boto3-stubs[essential]>=1.38.44",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
    # "numpy>=2.3.0",
    "numpy<2.0", # Para evitar conflictos con otras librerías que no soportan numpy 2.x
    "pydantic>=2.11.7",
    "cvat-sdk==2.42.0",
    "kml2geojson>=5.1.0",
    "opencv-python>=4.11.0.86",
    "matplotlib>=3.10.3",
    "layoutparser>=0.3.4",
    "pycocotools>=2.0.10",
    "pytest>=8.4.1",
    "scikit-learn>=1.7.1",
    "beautifulsoup4>=4.13.4",
    "deprecated>=1.2.18", 
]

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "modulo_utilidades"
module-root = ""
source-exclude = [
    "modulo_utilidades/main.py",
    "modulo_utilidades/database_comunication",
    "modulo_utilidades/labeling",
    "modulo_utilidades/s3_comunication",
    "modulo_utilidades/utils",
    "modulo_utilidades/webscrapping",
    "modulo_utilidades/config.py",
]
