name: picudo-rojo-project

services:
  keycloakdb:
    image: postgres:${POSTGRES_VERSION:-17.5}
    container_name: keycloakdb
    restart: unless-stopped
    volumes:
      - "${POSTGRES_DATA:-postgres_data}:/var/lib/postgresql/data" # Use named volume by default. If using Vagrant, one should copy the volume to destination folder specified in .env.dev to avoid issues with Hyper-V shared folders.
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    networks:
      - main

  keycloak_web:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-26.3}
    container_name: keycloak_web
    environment:
      # DATABASE CONFIGURATION
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      # SERVER CONFIGURATION
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: 8080

      # SECURITY CONFIGURATION
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT:-false} # Disable strict hostname checking
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS:-false} # Disable strict HTTPS checking
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED:-true} # Enable HTTP
      KC_PROXY_HEADERS: ${KC_PROXY_HEADERS:-null} # No proxy headers by default

      # BOOTSTRAP ADMIN USER
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-unsecurepassword}

      # LOGGING AND METRICS
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true

      # AUDITORIA
      # KC_EVENTS_LISTENERS: jpa,jboss-logging
      # # Guardara eventos de administración
      # KC_EVENTS_ENABLED: true
      # KC_EVENTS_STORE_ENABLED: true
    command: "${KEYCLOAK_START_COMMAND:-start-dev}"
    depends_on:
      - keycloakdb
    ports:
      - 7000:8080
    networks:
      - main

volumes:
  postgres_data:

networks:
  main:
