hsv_h: 0.0
hsv_s: 0.0  
hsv_v: 0.0
translate: 0.0
scale: 0.0
fliplr: 0.0
mosaic: 0.0
mixup: 0.0
copy_paste: 0.0
erasing: 0.0
crop_fraction: 1.0
auto_augment: null
degrees: 0.0
perspective: 0.0
shear: 0.0