# Este docker-compose.ddns.yml permite definir los servicios de CVAT que se ejecutarán en el entorno de ddns.
# Se ejecuta con el comando:
#   - docker compose --env-file .env.ddns -f docker-compose.yml -f docker-compose.ddns.yml up.

name: picudo-rojo-project

x-default_networks_anchor: &default_networks_anchor
  networks: !override
    - main

services:
  cvat_db: *default_networks_anchor

  cvat_redis_inmem: *default_networks_anchor

  cvat_redis_ondisk: *default_networks_anchor

  cvat_server:
      environment:
        DJANGO_SETTINGS_MODULE: settings
        CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-}
        CVAT_LDAP_USER: ${CVAT_LDAP_USER}
        CVAT_LDAP_PASSWORD: ${CVAT_LDAP_PASSWORD}
        AUTH_LDAP_SERVER_URI: ${AUTH_LDAP_SERVER_URI}
      networks: !override
        main:
          aliases:
            - cvat-server
      volumes:
        - ./custom-settings.py:/home/django/settings.py:ro
        - ./tests/allow_minio.sh:/etc/cvat/init.d/allow_minio.sh:ro

  cvat_utils: *default_networks_anchor

  cvat_worker_import: 
    <<: *default_networks_anchor
    volumes:
      - ./tests/allow_minio.sh:/etc/cvat/init.d/allow_minio.sh:ro

  cvat_worker_export: 
    <<: *default_networks_anchor
    volumes:
      - ./tests/allow_minio.sh:/etc/cvat/init.d/allow_minio.sh:ro

  cvat_worker_annotation: *default_networks_anchor

  cvat_worker_webhooks: *default_networks_anchor

  cvat_worker_quality_reports: *default_networks_anchor

  cvat_worker_chunks:
    <<: *default_networks_anchor
    volumes:
      - ./tests/allow_minio.sh:/etc/cvat/init.d/allow_minio.sh:ro

  cvat_worker_consensus: *default_networks_anchor  

  cvat_ui: *default_networks_anchor

  traefik: *default_networks_anchor

  cvat_opa:
    networks: !override
      main:
        aliases:
          - opa

  cvat_clickhouse:
    networks: !override
      main:
        aliases:
          - clickhouse

  cvat_vector:
    networks: !override
      main:
        aliases:
          - vector

  cvat_grafana:
    networks: !override
      main:
        aliases:
          - grafana

networks:
  main: