# Este docker-compose.local.minio.yml permite levantar CVAT con MinIO en el entorno local.
# Se ejecuta con el comando:
#   - docker compose --env-file .env.local -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.local.minio.yml up.
#   - docker compose --env-file .env.local -f docker-compose.yml -f docker-compose.local.yml -f docker-compose.local.fileserver.yml -f docker-compose.local.minio.yml up.
# Cambios:
#   - Se extiende agregando archivo que se ejecuta en la configuración inicial de CVAT. Este archivo obtiene la IP de Minio para setear el la variable de entorno SMOKESCREEN_OPTS de forma dinámica. Esto permite que SMOKESCREEN_OPTS no controle la IP de Minio. NOTA: Si se entra al contenedor la variable de entorno SMOKESCREEN_OPTS no está definida, pero está funcionando. Una opción sería obtener la IP y setearla en las variables de entorno de forma manual.

x-allow-minio: &allow-minio
  volumes:
    - ./tests/allow_minio.sh:/etc/cvat/init.d/allow_minio.sh:ro

services:
  cvat_server: 
    <<: *allow-minio
  cvat_worker_export:
    <<: *allow-minio
  cvat_worker_import:
    <<: *allow-minio
  cvat_worker_chunks:
    <<: *allow-minio