# Este docker-compose.local.yml permite definir los servicios de CVAT que se ejecutarán en el entorno local.
# Se ejecuta con el comando:
#   - docker compose --env-file .env.local -f docker-compose.yml -f docker-compose.local.yml up.
# Cambios:
#   - Se agrega el nombre del proyecto, para que todos los servicios de CVAT tengan un prefijo.
#   - Se sustituye la red cvat por la red main en todos los servicios.
# NOTA: Cuando se ejecuta con el flag --env-file .env.local, se aplica interpolación de variables de entorno en el docker-compose.yml. Cuando se pasa el archivo con la propiedad env_file, se pasan las variables de entorno a los contenedores.

# https://docs.docker.com/reference/compose-file/merge/
name: picudo-rojo-project

x-default_services_properties: &default_services_properties
  networks: !override
    - main

services:
  cvat_db: *default_services_properties

  cvat_redis_inmem: *default_services_properties

  cvat_redis_ondisk: *default_services_properties

  cvat_server:
    networks: !override
      main:
        aliases:
          - cvat-server

  cvat_utils: *default_services_properties

  cvat_worker_import: *default_services_properties

  cvat_worker_export: *default_services_properties

  cvat_worker_annotation: *default_services_properties

  cvat_worker_webhooks: *default_services_properties

  cvat_worker_quality_reports: *default_services_properties

  cvat_worker_analytics_reports: *default_services_properties

  cvat_worker_chunks: *default_services_properties

  cvat_ui: *default_services_properties

  traefik: *default_services_properties

  cvat_opa:
    networks: !override
      main:
        aliases:
          - opa

  cvat_clickhouse:
    networks: !override
      main:
        aliases:
          - clickhouse

  cvat_vector:
    networks: !override
      main:
        aliases:
          - vector

  cvat_grafana:
    networks: !override
      main:
        aliases:
          - grafana

networks:
  main:
