# Este docker-compose.ddns.minio.yml permite levantar CVAT con MinIO en el entorno ddns.
# Se ejecuta con el comando:
#   - docker compose --env-file .env.ddns -f docker-compose.yml -f docker-compose.ddns.yml -f docker-compose.ddns.minio.yml up.
#   - docker compose --env-file .env.ddns -f docker-compose.yml -f docker-compose.ddns.yml -f docker-compose.local.fileserver.yml -f docker-compose.ddns.minio.yml up.
# Cambios:
#   - Se agrega la variable de entorno SMOKESCREEN_OPTS que apunta a la IP de Minio.
# NOTA: Smokescreen por defecto bloquea todas las IPs privadas, no las públicas. Hay que obtener las IP de los servcios, ya que la variable de entorno SMOKESCREEN_OPTS recibe una IP:PUERTO. Otra opción, es ejecutar un .sh para setear esta variable antes de correr docker compose. También cabe destacar que para agregar el storage hay que hacerlo mediante el IP o poner la siguiente regla en el hosts `127.0.0.1 minio`.

x-allow-minio: &allow-minio
  environment:
    SMOKESCREEN_OPTS: '--allow-address=172.18.0.3'

services:
  cvat_server: 
    <<: *allow-minio
  cvat_worker_export:
    <<: *allow-minio
  cvat_worker_import:
    <<: *allow-minio
  cvat_worker_chunks:
    <<: *allow-minio