# Este docker-compose.local.yml permite definir los servicios de CVAT que se ejecutarán en el entorno local.
# Se ejecuta con el comando:
#   - docker compose --env-file .env.local -f docker-compose.yml -f docker-compose.local.yml up.
# Cambios:
#   - Se agrega el nombre del proyecto, para que todos los servicios de CVAT tengan un prefijo.
#   - Se sustituye la red cvat por la red main en todos los servicios.
# NOTA: Cuando se ejecuta con el flag --env-file .env.local, se aplica interpolación de variables de entorno en el docker-compose.yml. Cuando se pasa el archivo con la propiedad env_file, se pasan las variables de entorno a los contenedores.

# https://docs.docker.com/reference/compose-file/merge/
name: picudo-rojo-project

x-default_services_properties:
  networks: !override &default_networks_anchor
    - main

x-default_volumes_top_anchor: 
  volumes: &default_volumes_anchor
      - ./cvat_data:/home/django/data
      - ./cvat_keys:/home/django/keys
      - ./cvat_logs:/home/django/logs

x-default_networks_volumes_properties: &default_networks_volumes_anchor
  networks: *default_networks_anchor
  volumes: *default_volumes_anchor

services:
  cvat_db:
    volumes:
      - ./cvat_db:/var/lib/postgresql/data
    networks: *default_networks_anchor

  cvat_redis_inmem:
    networks: *default_networks_anchor

  cvat_redis_ondisk:
    networks: *default_networks_anchor

  cvat_server:
    volumes: *default_volumes_anchor
    networks: !override
      main:
        aliases:
          - cvat-server

  cvat_utils:
    <<: *default_networks_volumes_anchor

  cvat_worker_import: 
    <<: *default_networks_volumes_anchor

  cvat_worker_export: 
    <<: *default_networks_volumes_anchor

  cvat_worker_annotation: 
    <<: *default_networks_volumes_anchor

  cvat_worker_webhooks: 
    <<: *default_networks_volumes_anchor

  cvat_worker_quality_reports: 
    <<: *default_networks_volumes_anchor

  cvat_worker_analytics_reports: 
    <<: *default_networks_volumes_anchor

  cvat_worker_chunks: 
    <<: *default_networks_volumes_anchor

  cvat_ui: 
    networks: *default_networks_anchor

  traefik: 
    networks: *default_networks_anchor

  cvat_opa:
    networks: !override
      main:
        aliases:
          - opa

  cvat_clickhouse:
    volumes:
      - ./cvat_events_db:/var/lib/clickhouse/
    networks: !override
      main:
        aliases:
          - clickhouse

  cvat_vector:
    networks: !override
      main:
        aliases:
          - vector

  cvat_grafana:
    networks: !override
      main:
        aliases:
          - grafana

networks:
  main:
