# Este docker-compose.local.yml permite definir los servicios de CVAT que se ejecutarán en el entorno local.
# Se ejecuta con el comando:
#   - docker compose --env-file .env.ddns -f docker-compose.yml -f docker-compose.ddns.yml -f docker-compose.ddns.ldap.yml up.

services:
  cvat_server:
    environment:
      CVAT_LDAP_USER: ${CVAT_LDAP_USER}
      CVAT_LDAP_PASSWORD: ${CVAT_LDAP_PASSWORD}
    volumes:
      - ./ldap-csrf-ddns-settings.py:/home/django/settings.py:ro