# CONFIGURACION GENERAL
environment: "LOCAL" # Opciones: PRODUCTION, LOCAL, SCALEWAY

seed: 42
# Logger
logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s - %(message)s"
  level: "INFO"

mongodb:
  database: ${MONGODB_INITDB_DATABASE}
  host: ${MONGODB_SERVER_HOST}
  port: ${MONGODB_SERVER_PORT}
  user: ${MONGODB_USER}
  password: ${MONGODB_PASSWORD}
  connection_string: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_SERVER_HOST}:${MONGODB_SERVER_PORT}/${MONGODB_INITDB_DATABASE}"

cvat:
  url: ${CVAT_URL}
  user: ${CVAT_USER}
  password: ${CVAT_PASSWORD}
  export_format: "COCO 1.0"
  task_export_path: "annotations\\instances_default.json"
  job_export_path: "annotations\\instances_default.json"

minio:
  bucket: ${MINIO_BUCKET}
  endpoint_url: ${MINIO_ENDPOINT_URL}
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  region: nl-ams
  paths:
    images: "imagenes"
    metadata: "imagenes_metadatos"
    patches: "patches"
    cutouts: "recortes"
    cutouts_metadata: "recortes_metadatos"

folders:
  download_folder: "downloads"
  patches_patches: "downloads/patches"
  raw_dataset_folder: "downloads/raw_dataset"
  yolo_dataset: "downloads/yolo_dataset"

# ----------------------------------------------------------------------------
# APP: WEBSCRAPPING
# URLs de servicios externos
urls:
  main_page: "https://gis.montevideo.gub.uy/pmapper/map.phtml?&config=default&me=548000,6130000,596000,6162000"
  toc: "https://intgis.montevideo.gub.uy/pmapper/incphp/xajax/x_toc.php?"
  generate_zip: "https://intgis.montevideo.gub.uy/sit/php/common/datos/generar_zip2.php?nom_jpg=/inetpub/wwwroot/sit/mapserv/data/fotos_dron/{id}&tipo=jpg"
  download_zip: "https://intgis.montevideo.gub.uy/sit/tmp/{id}.zip"
  js: "https://intgis.montevideo.gub.uy/pmapper/config/default/custom.js"

# Headers para las peticiones HTTP
headers:
  common:
    User-Agent: "Mozilla/5.0"
  toc:
    User-Agent: "Mozilla/5.0"
    Referer: "https://gis.montevideo.gub.uy/pmapper/map.phtml?&config=default&me=548000,6130000,596000,6162000"
    X-Requested-With: "XMLHttpRequest"
    Content-Type: "application/x-www-form-urlencoded"

# Cuerpo de las peticiones
request_body:
  toc:
    dummy: "dummy"

# Configuracion de los parches
patches:
  tile_size: [4096, 4096]
  over_lap: 400
  purge_white_images: true

# ----------------------------------------------------------------------------
# APP: ETIQUETADO
coco_dataset:
  info:
    description: "Conjunto de imágenes para la detección del picudo rojo"
    url: "https://picudo-rojo.org"
    version: "1.0"
    year: 2025
    contributor: "Intendencia de Montevideo"
    date_created: "2025/01/01"
  licenses:
    - id: 1
      name: "CC BY-NC-SA 4.0"
      url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  categories:
    - id: 1
      name: "palmera-sana"
      supercategory: ""
    - id: 2
      name: "palmera-inf-leve"
      supercategory: ""
    - id: 3
      name: "palmera-inf-grave"
      supercategory: ""
    - id: 4
      name: "palmera-muerta"
      supercategory: ""
    - id: 5
      name: "palmera"
      supercategory: ""

layoutparser:
  draw_box:
    box_width: 10
    box_alpha: 0
    color_map:
      palmera-sana: "green"
      palmera-inf-leve: "yellow"
      palmera-inf-grave: "orange"
      palmera-muerta: "red"
      palmera: "blue"
    show_element_id: true

opencv_draw:
  draw_box:
    box_width: 5
    box_alpha: 0.5
    color_map:
      1: [0, 255, 0]
      2: [255, 255, 0]
      3: [255, 165, 0]
      4: [255, 0, 0]
      5: [0, 0, 255]
    font_scale: 0.5
    font_thickness: 2

google_maps:
  mid: 1yCQ986yfEy6SmUXEREmedCEptZEA_h0
  base_url: "https://www.google.com/maps/d/u/0/kml"
  categories:
    - id: 1
      name: "palmera-google-maps"
      supercategory: ""

georeferenciacion:
  sistema_referencia: "WGS84"
  proyeccion: "UTM 21S"
  codigo_epsg: "EPSG:32721"

bbox_size:
  width: 10
  height: 10
