# $env:ENVIRONMENT="dev"; vagrant up

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"
  config.vm.hostname = "ceia-proyecto-final-develop"
  
  # Configuración de red bridge (eth1)
  config.vm.network "public_network",
    bridge: "Intel(R) Wi-Fi 6E AX211 160MHz",
    use_dhcp_assigned_default_route: true  # Prioriza esta interfaz

  config.vm.disk :disk, size: "50GB", primary: true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4 # Número de CPUs asignadas a la VM
    vb.memory = "8192" # 32 GB de RAM asignados a la VM
    vb.name = "ceia-proyecto-final-develop" # Nombre de la VM en VirtualBox

    # Deshabilita la interfaz NAT (eth0) como ruta predeterminada
    vb.customize ["modifyvm", :id, "--nic1", "nat"]
    vb.customize ["modifyvm", :id, "--nicpromisc1", "deny"] 
  end

  config.vm.provision "setup-vm-network", type: "shell", path: "vagrant-scripts/01-setup-network.sh"
  config.vm.provision "install-dependencies", type: "shell", path: "vagrant-scripts/02-install-dependencies.sh"
  config.vm.provision "setup-firewall", type: "shell", path: "vagrant-scripts/03-configure-firewall.sh"
  # To run: vagrant up --provision-with start-services
  # To run: vagrant provision --provision-with start-services
  environment = ENV['ENVIRONMENT'] || 'dev' # Por defecto, asume 'dev'

  if environment == 'prod'
    puts "Script de produccion"
    config.vm.provision "start-services", type: "shell", path: "vagrant-scripts/04-start-prod-services.sh", run: "never"
  else
    puts "Script de desarrollo"
    config.vm.provision "start-services", type: "shell", path: "vagrant-scripts/04-start-dev-services.sh", run: "never"
  end
end