server {
    listen 80;
    server_name _;

    # Desactivar sendfile para evitar el error con volúmenes compartidos
    sendfile off;

    root /usr/share/nginx/html;
    index maintenance.html;
    # index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}